### ISSUE TITLE
Pulling submodules

### ISSUE THREAD

**Issue by siriusxiv** [avr-aics-riken/HIVE#25]
When we pull submodules through

```
git submodule update --init
```

The submodules are not updated automatically to the latest commit. 
As a result, I have to manually pull all submodules using

```
git pull origin master
```

in the submodule's directory.
In HIVE's case, is it a planned functionality or an issue?

(This is especially the case for the SURFACE submodule, bugs were corrected in latest commits which are not pulled automatically when updating submodules)

**Comment by syoyo** [comment]
Yes, you need manually pull in the submodule or use `git submodule foreach git pull origin master`

http://stackoverflow.com/questions/1030169/easy-way-pull-latest-of-all-submodules
